### PR TITLE
Add Windows support

### PR DESCRIPTION
**Pull request by dranov**
Here's a summary of the changes:

- Added crate `path-slash` to convert Windows paths to Unix-style paths for display purposes. Otherwise the test snapshots fail because the test path is displayed differently on Windows (with `\` rather than `/`).
- Handle Windows-style newlines (`\r\n`) when interacting with the SMT solvers.
- Add Powershell script to download solvers on Windows, and mention this in the README.

### CODE REVIEW

**Comment by dranov** [comment]
There was a merge commit I did using the GitHub interface, which didn't have the `Signed-off-by` line, so I force-pushed to remove it.

**Comment by tchajed** [comment]
Oded and I discussed it and we don't think it's worth it for us to maintain Windows support, especially since WSL seems to work well for this use case.

That said, some of the changes in this PR are general improvements and should also make the code fairly compatible. If you remove the PowerShell scripts I'd be happy to merge everything else. If we (or you!) decide to implement cargo xtask, then I think adding (somewhat unofficial) Windows support would become easy.

**Comment by dranov** [comment]
Sure, I understand Windows is not a priority. That's okay. (I personally use WSL 2 myself.)

I don't have the bandwidth to look into `cargo-xtask` now, so I've removed the PowerShell scripts.

**Comment by tchajed** [comment]
Thanks for updating the PR!

**Pull request merged**
